### ISSUE TITLE
Not Python 3 compatible

### ISSUE THREAD

**Issue by TXBDan** [jthorniley/pyusb2ax#1]
Hello,

Thanks a ton for creating this wrapper. I'm sure you're well aware that this isn't Python 3 compatible. Any plans for a Python 3 version? Even after updating the prints and exception code in the setup.py script, i'm getting:

Traceback (most recent call last):
  File "setup.py", line 211, in <module>
    cmdclass = {"build_ext":build_bindings} )
  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.4/distutils/command/install.py", line 583, in run
    self.run_command('build')
  File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.4/distutils/command/build.py", line 126, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 197, in run
    patch_dxl_sdk()
  File "setup.py", line 133, in patch_dxl_sdk
    print (sp.communicate(input=patch)[0])
  File "/usr/lib/python3.4/subprocess.py", line 960, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.4/subprocess.py", line 1602, in _communicate
    input_view = memoryview(self._input)
TypeError: memoryview: str object does not have the buffer interface

Thanks again!

**Comment by jthorniley** [comment]
Hi,

I'm afraid I don't have the device anymore and I never got around to making it work on python 3.

I think I've seen this error with other conversions though, the problem can be fixed in this frame:

File "setup.py", line 133, in patch_dxl_sdk
print (sp.communicate(input=patch)[0])

So if you find that line, try replacing it with these two:

```
patch_bytes = bytes(patch, 'UTF-8')
print(sp.communicate(input=patch_bytes)[0])
```

I'm guessing this a bit from here: http://stackoverflow.com/questions/5471158/typeerror-str-does-not-support-the-buffer-interface

But it will be easier for you to test it if you've got the device.

James

**Comment by TXBDan** [comment]
Great, that fixed it, thanks.

It had trouble downloading the Robotis linux SDK so I did it manually and it all installed fine. 

Now I’ll try it out.

Thanks again,

Dan
